### PR TITLE
Fixed double fclose(f) when calling export_wav

### LINKED ISSUE #293: export wav produces an erroneous file
I've compiled the latest klystrack version (using the howto there: https://github.com/kometbomb/klystrack/wiki/HowToCompile) and while everything seems to work fine, when I export to wav, the resulting file is not correct. I can play it with VLC, but sonic-visualiser and audacity report this as an empty file.

When trying to convert it to flac, the flac command returns:
ERROR: 'data' chunk has size of 0

But I can export wav for the same track from klystrack 1.7.2 for example.

I've tried with a fresh new project, it 's the same export problem.

### PR DESCRIPTION
**Pull request by nalquas**
Turns out fclose(f) is called inside of ww_finish, which is called inside of export_wav. Therefore, closing the already closed file after calling export_wav would result in a crash.

This should fix #293.

### CODE REVIEW

File: src/export.c [hunk 1]
```diff
@@ -129,8 +129,6 @@ bool export_wav(MusSong *song, CydWavetableEntry * entry, FILE *f, int channel)
 		}
 	}
 	
-	return true; // Successful (not aborted)
```
Comment (kometbomb) [inline src/export.c:132]: I think this is the main issue here: it returns before deinit (also the cyd instance isn't deinit and ww_finish doesn't get to free the memory). Perhaps instead of the revert we could just set a success flag here and return that very last.

Comment (kometbomb) [reply src/export.c:132]: Or, just make sure ww_finish is called the return (be it a success or a failure)

Comment (nalquas) [reply src/export.c:132]: If we really want `export_wav` to continue to return a success boolean, having a success flag and returning that at the end of the function is the way to go.
However, I only made `export_wav` return a boolean to indicate whether `fclose` still needs to be called. If we call `ww_finish` every time, then there's no need for calling `fclose` after `export_wav`, thus making the success boolean unnecessary.

Comment (nalquas) [reply src/export.c:132]: These changes would do what you suggest, should I add them to the pull request?
```diff
diff --git a/src/export.c b/src/export.c
index 854ea3c..7454329 100644
--- a/src/export.c
+++ b/src/export.c
@@ -38,8 +38,10 @@ OTHER DEALINGS IN THE SOFTWARE.
 
 extern GfxDomain *domain;
 
-void export_wav(MusSong *song, CydWavetableEntry * entry, FILE *f, int channel)
+bool export_wav(MusSong *song, CydWavetableEntry * entry, FILE *f, int channel)
 {
+	bool success = false;
+	
 	MusEngine mus;
 	CydEngine cyd;
 	
@@ -129,6 +131,8 @@ void export_wav(MusSong *song, CydWavetableEntry * entry, FILE *f, int channel)
 		}
 	}
 	
+	success = true;
+	
 abort:;
 	
 	ww_finish(ww);
@@ -138,5 +142,7 @@ abort:;
 	cyd_deinit(&cyd);
 	
 	song->flags &= ~MUS_NO_REPEAT;
+	
+	return success;
 }
 
diff --git a/src/export.h b/src/export.h
index 8ede779..aa746da 100644
--- a/src/export.h
+++ b/src/export.h
@@ -28,6 +28,6 @@ OTHER DEALINGS IN THE SOFTWARE.
 
 #include "snd/music.h"
 
-void export_wav(MusSong *song, CydWavetableEntry * entry, FILE *f, int channel);
+bool export_wav(MusSong *song, CydWavetableEntry * entry, FILE *f, int channel);
 
 #endif
```

Comment (kometbomb) [reply src/export.c:132]: Perhaps it's good that it returns the success even if we don't actually use that (yet). :+1:
